
CREATE TABLE KNMI_dagwaarnemingen (
    STN INT NOT NULL,
    YYYYMMDD DATE NOT NULL,
    DDVEC INT,
    FHVEC INT,
    FG INT,
    FHX INT,
    FHXH INT,  
    FHN INT, 
    FHNH INT,  
    FXX INT, 
    FXXH INT,   
    TG INT,   
    TN INT,  
    TNH INT,   
    TX INT,  
    TXH INT, 
    T10N INT,
    T10NH INT,   
    SQ INT,   
    SP INT,    
    Q INT,   
    DR INT,   
    RH INT,  
    RHX INT, 
    RHXH INT,   
    PG INT,   
    PX INT,  
    PXH INT,   
    PN INT,  
    PNH INT,  
    VVN INT, 
    VVNH INT,  
    VVX INT, 
    VVXH INT,   
    NG INT,   
    UG INT,   
    UX INT,  
    UXH INT,   
    UN INT,  
    UNH INT, 
    EV24 INT,
  PRIMARY KEY (STN, YYYYMMDD)
);